defmodule PurintaDashboardWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :purinta_dashboard

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  #
  # `secure: true` (enabled in prod via the :session_secure config) marks
  # the cookie Secure so it is never sent over plain HTTP. Left off in
  # dev/test so http://localhost keeps working.
  @session_options [
    store: :cookie,
    key: "_purinta_dashboard_key",
    signing_salt: "aeKwL1+9",
    same_site: "Lax",
    secure: Application.compile_env(:purinta_dashboard, :session_secure, false)
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # User-authenticated socket for application channels (`global`,
  # `user:<id>`). Auth is by signed Phoenix.Token from SharedData. No
  # longpoll fallback — clients on networks that block WebSockets fall
  # back to plain Inertia until the network is fixed.
  socket "/socket", PurintaDashboardWeb.UserSocket, websocket: true, longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :purinta_dashboard,
    gzip: not code_reloading?,
    only: PurintaDashboardWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Self-served ex_doc. `mix docs` writes HTML + search index to `doc/`
  # (gitignored). `DocsIndexRedirect` bounces `/dev/docs` and
  # `/dev/docs/` to `/dev/docs/index.html` so relative links inside the
  # generated HTML resolve against the right directory.
  if Application.compile_env(:purinta_dashboard, :dev_routes) do
    plug PurintaDashboardWeb.Plugs.DocsIndexRedirect
    plug Plug.Static, at: "/dev/docs", from: Path.expand("../../doc", __DIR__)
  end

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :purinta_dashboard
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug PurintaDashboardWeb.Router
end
