import Config

# Configure your database
config :purinta_dashboard, PurintaDashboard.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "purinta_dashboard_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
#
# The CI E2E job builds assets ahead of time and starts this server with
# DISABLE_WATCHERS=true, so esbuild/tailwind aren't spawned in --watch mode
# (they'd race the prebuilt bundle and the suite could hit the server before
# they settle). Leave the env var unset locally for live rebuilds.
watchers =
  if System.get_env("DISABLE_WATCHERS") in ~w(1 true) do
    []
  else
    [
      esbuild:
        {Esbuild, :install_and_run,
         [
           :purinta_dashboard,
           ~w(--sourcemap=inline --watch --define:process.env.NODE_ENV="development")
         ]},
      node: ["build/watch-ssr-pages.js", cd: Path.expand("../assets", __DIR__)],
      esbuild_ssr: {Esbuild, :install_and_run, [:purinta_dashboard_ssr, ~w(--watch)]},
      tailwind: {Tailwind, :install_and_run, [:purinta_dashboard, ~w(--watch)]}
    ]
  end

config :purinta_dashboard, PurintaDashboardWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  # Used by `Endpoint.url/0` (e.g. when building email links). Prod
  # overrides this in runtime.exs from PHX_HOST + standard https port.
  url: [host: "localhost", port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "cxv85lAQCKdwQQYuRC7eeX4DytlQDl7mBLv283CTNcnpqtcTd2lfYbJmD9oa9DgV",
  watchers: watchers

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :purinta_dashboard, PurintaDashboardWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/purinta_dashboard_web/router\.ex$"E,
      ~r"lib/purinta_dashboard_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :purinta_dashboard, dev_routes: true

# Disable auth rate limiting in development. The Playwright E2E suite drives
# this server and legitimately makes many requests from one IP; throttling
# is a production concern (and the limiter is covered by rate_limit_test).
# Flip to `true` if you want to exercise the limiter locally.
config :purinta_dashboard, rate_limit_enabled: false

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
