import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :purinta_dashboard, PurintaDashboardWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Mark the session cookie Secure in production (read at compile time by
# the endpoint's @session_options). Prod is served over HTTPS, so the
# cookie must never travel over plain HTTP.
config :purinta_dashboard, session_secure: true

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :purinta_dashboard, PurintaDashboardWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Gracefully fall back to client-side rendering on SSR errors
config :inertia, raise_on_ssr_failure: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
