defmodule PurintaDashboard.ContextTest do
  use PurintaDashboard.DataCase, async: true

  import PurintaDashboard.Factory

  alias PurintaDashboard.Accounts
  alias PurintaDashboard.Accounts.User

  # Exercises the CRUD helpers generated by `use PurintaDashboard.Context`
  # through `Accounts`, which is the real consumer of the macro.

  describe "list helpers" do
    test "list_users/0 returns every row" do
      u1 = :user |> build() |> insert()
      u2 = :user |> build() |> insert()
      ids = Accounts.list_users() |> Enum.map(& &1.id) |> Enum.sort()
      assert ids == Enum.sort([u1.id, u2.id])
    end

    test "list_users_ok/0 wraps the list in an :ok tuple" do
      :user |> build() |> insert()
      assert {:ok, [%User{}]} = Accounts.list_users_ok()
    end
  end

  describe "get helpers" do
    test "get_user_ok/1 returns {:ok, user} or {:error, :not_found}" do
      user = :user |> build() |> insert()
      assert {:ok, %User{id: id}} = Accounts.get_user_ok(user.id)
      assert id == user.id
      assert {:error, :not_found} = Accounts.get_user_ok(Ecto.UUID.generate())
    end

    test "get_user/1 returns the user or nil" do
      user = :user |> build() |> insert()
      assert %User{} = Accounts.get_user(user.id)
      assert Accounts.get_user(Ecto.UUID.generate()) == nil
    end

    test "get_user!/1 returns the user or raises" do
      user = :user |> build() |> insert()
      assert %User{} = Accounts.get_user!(user.id)
      assert_raise Ecto.NoResultsError, fn -> Accounts.get_user!(Ecto.UUID.generate()) end
    end

    test "get_user_by_ok/1 and get_user_by/1 look up by clauses" do
      user = :user |> build() |> insert()
      assert {:ok, %User{}} = Accounts.get_user_by_ok(email: user.email)
      assert %User{} = Accounts.get_user_by(email: user.email)
      assert Accounts.get_user_by(email: "missing@example.com") == nil
    end
  end

  describe "count / change / delete helpers" do
    test "count_users/0 returns the row count" do
      assert Accounts.count_users() == 0
      :user |> build() |> insert()
      assert Accounts.count_users() == 1
    end

    test "change_user/2 returns a changeset built from the configured changeset fn" do
      user = :user |> build() |> insert()
      assert %Ecto.Changeset{} = Accounts.change_user(user, %{})
    end

    test "delete_user/1 removes the row" do
      user = :user |> build() |> insert()
      assert {:ok, %User{}} = Accounts.delete_user(user)
      assert Accounts.get_user(user.id) == nil
    end
  end

  describe "filter override" do
    test "filter_users/2 defaults to a passthrough when not overridden" do
      assert Accounts.filter_users(User, some: :filter) == User
    end
  end
end
